---
title: "Mini-Project 2!"
author: "Joarvi Edwards, Kira Hill, Elise Snoey"
date: "October 31, 2017"
output: html_document
---


## Loading the data

This project is so interesting and relevant to my life!

```{r, include=FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
library(tidyverse)
glimpse(house_elections)
glimpse(candidates)
glimpse(committees)
glimpse(contributions)
```

#Tried join to get cand_id and $ together
```{r}
type <- c("24E", "24A")
excand <- candidates %>%
  inner_join(contributions, by = "cand_id") %>%
  filter(transaction_type == type, cand_office == "P") %>%
  select(cand_name, cand_party_affiliation, transaction_type, transaction_amt) %>%
  group_by(cand_name, transaction_type) %>%
  mutate(total_transaction_amt = sum(transaction_amt))
glimpse(excand)
```

## Build a ggplot of selected data
```{r}
# have not been able to get the ggplot to work yet
#ggplot(excand, aes(x = cand_name, y = total_transaction_amt)) +
  #geom_histogram()
